[theme]
primaryColor = "#27776C"
backgroundColor = "#FBFAF7"
secondaryBackgroundColor = "#EFEDE6"
textColor = "#23352F"
font = "sans serif"

[server]
address = "127.0.0.1"
maxUploadSize = 10

[browser]
gatherUsageStats = false
